---
title: "Untitled"
author: "Ricardo"
date: "21/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Evaluación de las exposiciones de Minería de Datos. GIN2 2020-2021.

Título del trabajo:

Nombre del presentador:

Hora inicial:

Hora final:

Evaluador:

Criterio

Criterio   -| Descripción  -| Calificación
------------|-----------------------------------------------------|----------------
Estructura    | *El orador saluda y hace una introducción en la que se exponen brevemente las ideas principales que se desarrollarán en la presentación.|
(2 puntos) | *La información se presenta de manera lógica y coherente para que la audiencia pueda seguir.|
| * La presentación se ha ajustado al tiempo previsto|
------------|-----------------------------------------------------|----------------
Desarrollo | Describe el contexto del problema y la metodología estadística que se va a emplear.|
(5 puntos) | Incluye la fuente de datos y la descripción de cada una de las variables que la conforman.|
  | Realiza un análisis exploratorio de los datos.|
  | Ha aplicado correctamente las técnicas estudiadas en clase y ha presentado algunos aspectos novedosos.|
  | Se discuten los resultados obtenidos conjuntamente con las implicaciones que tienen.|
------------|-----------------------------------------------------|----------------
Preparación
(3 puntos)
------------|-----------------------------------------------------|----------------

Total
(10 puntos)
------------|-----------------------------------------------------|----------------

*  Muestra dominio del material que expone
*  Respondió apropiadamente las preguntas que le fueron
formuladas
*  Preparó material para la exposición diferente al informe
escrito
Suma de los puntos de los apartados anteriores

Nota

1. Swiss Market
Víctor: saludo bien. Visualización de la serie. Trabajo tendencia y Regular
la conclusión. Preparó material de la exposición.
2. France Market: Arturo modelo de tendencia de orden 2 es 226, alisado
simple Bien. Faltó un poco de análisis. Usaron el RMarkdown
3. DaX: expone María. Prepararon presentación
Muy bien explicación del conjunto de datos. Bastante
4. UK : expone Xavi No han preprado material para la expo sólo .rmd para
entregar. Tendencia determinística de orden 2 .Trabajo bastante.
5.

Rúbrica para la evaluación de las exposiciones de Ampliación
Título del trabajo:
Nombre del presentador:

Hora inicial:

Hora final:

Evaluador:

Criterio

Descripción

Estructura

* 
* 

(2 puntos)

* 

* 

Planteamiento
del problema y
Análisis
descriptivo de los
datos
(2 puntos)

* 
* 
* 

El orador saluda a la audiencia y se presenta.
Hay una introducción en la que se exponen brevemente
las ideas principales que se desarrollarán en la
presentación.
Se desarrolla cada una de las ideas principales. Queda
claro cuándo ha acabado una parte y empieza la
siguiente.
El orador resume las ideas principales de la exposición.
Describe el contexto del problema y la metodología
estadística que se van a emplear.
Suele incluirse la fuente de datos y la descripción de cada
una de las variables que la conforman.
Describe estadísticamente los datos previos al modelado
de éstos.

Nota

* 

El modelo ajustado es adecuado, ¿se han seguido las
técnicas estudiadas en clase? ¿se han añadido otras
técnicas?

Conclusiones y
* 
recomendaciones

Se discuten los resultados obtenidos conjuntamente
con las implicaciones que tienen

Ajuste de
modelos y
validación
(2.5 puntos)

(1.5 puntos)

Ajuste al tiempo

* 

(1 punto)

Valoración global
(1 punto)
Total
(maximo. 10 puntos)

* 

La presentación se ha ajustado al tiempo previsto (20
minutos máximo).
La presentación me ha gustado

Suma de los puntos de los apartados anteriores

